# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers :
        default :
            web_path : ~
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature_home:
            quality: 75
            filters:
                thumbnail:
                    size: [634.333, 400]
                    mode: outbound
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [634.333, 800]
                    mode: outbound
                    position: center
        normal:
            quality: 90
            filters:
                scale:
                    dim: [800, 800]
                   