vich_uploader:
    db_driver: orm
    
    mappings:
            product_image:
                uri_prefix: /images/products
                upload_destination: '%kernel.project_dir%/public/images/products'
                namer: Vich\UploaderBundle\Naming\UniqidNamer
            galerie_image:
                uri_prefix: /images/galeries
                upload_destination: '%kernel.project_dir%/public/images/galeries'
                namer: Vich\UploaderBundle\Naming\UniqidNamer
            press_image:
                uri_prefix: /images/presses
                upload_destination: '%kernel.project_dir%/public/images/presses'
                namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
